= GCC SSH Image
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Buildah: https://buildah.io/[Buildah]
:CLion: https://www.jetbrains.com/clion/[CLion]
:Fedora: https://getfedora.org/[Fedora]
:Fedora-Silverblue: https://silverblue.fedoraproject.org/[Fedora Silverblue]
:GCC: https://gcc.gnu.org/[GCC]
:OpenSSH: https://www.openssh.com/[OpenSSH]
:Podman: https://podman.io/[Podman]
:Visual-Studio-Code: https://code.visualstudio.com/[Visual Studio Code]

image:https://img.shields.io/github/workflow/status/jwillikers/gcc-ssh-image/CI/main[GitHub Workflow Status]

A container image for running the {GCC} toolchain from an {OpenSSH} server, built on {Fedora}.
Comes complete with CMake, Conan, Ninja, and Clang tools.

== Synopsis

This container is meant to be used with IDE's that support remote development over SSH, such as {CLion} and {Visual Studio Code}.
You might find this workflow particularly helpful if you develop on an immutable base operating system, such as {Fedora Silverblue}.

Supported architectures:: `amd64`, `arm32v7`, `arm64v8`
User:: user
Password:: password

== Quick Start

To use the GCC toolchain inside the container, execute commands via {Podman}.

[source,sh]
----
➜ podman run --rm -p 2222:22 --volume "$HOME":/home/user:Z -dt --name gcc-ssh quay.io/jwillikers/gcc-ssh:latest
----

== Build

This project uses {Buildah} and {Podman} for building and testing the image.
To ensure the shell scripts are kept in good working order, the project uses ShellCheck and shfmt.
A set of pre-commit checks are readily available to ensure your code is up-to-spec before it is committed.
Instructions for setting up a development environment, building the image, and testing the image follow.
These instructions are intended for users of {Fedora-Silverblue}.
Standard Fedora users can just remove the `toolbox run` commands.

I should probably just provide a container with a Bash development environment, shouldn't I?

. Install the dependencies.
+
[source,sh]
----
➜ toolbox run sudo dnf -y install buildah git podman pre-commit ShellCheck shfmt
----

. Clone this repository.
+
[source,sh]
----
➜ toolbox run git -C ~/Projects clone git@github.com:jwillikers/gcc-ssh-image.git
----

. Change into the project directory.
+
[source,sh]
----
➜ cd ~/Projects/gcc-ssh-image
----

. Install pre-commit's Git hooks
+
[source,sh]
----
➜ toolbox run pre-commit install
----

. Run the shell script to build the image.
+
[source,sh]
----
➜ toolbox run ~/Projects/gcc-ssh-image/gcc-ssh-image.sh
----

. Test the image with the `test.sh` shell script.
+
[source,sh]
----
➜ toolbox run ~/Projects/gcc-ssh-image/test.sh
----

== Learn More

* https://blog.jetbrains.com/clion/2020/01/using-docker-with-clion/[Using Docker with CLion]
* https://code.visualstudio.com/docs/remote/ssh[Visual Studio Code - Remote Development using SSH]

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://asciidoctor.org/[Asciidoctor]
* {Buildah}
* {Fedora}
* {Fedora-Silverblue}
* {GCC}
* https://git-scm.com/[Git]
* https://www.linuxfoundation.org/[Linux]
* {OpenSSH}
* {Podman}
* https://www.python.org/[Python]
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[Code of Conduct] file.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[license file].

© 2021 Jordan Williams

== Authors

mailto:{email}[{author}]
